AllCops:
  # Default formatter will be used if no `-f/--format` option is given.
  DefaultFormatter: progress
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the `-D/--display-cop-names`
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding `DisplayStyleGuide`, or by giving the
  # `-S/--display-style-guide` option.
  DisplayStyleGuide: false
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
